name: 'Upload to App Store'
description: 'TODO'
inputs:
  ipa_path:
    description: 'TODO'
  appstore_issuer:
    description: 'TODO'
  appstore_key_id:
    description: 'TODO'
  appstore_key_content:
    description: 'TODO'
runs:
  using: 'composite'
  steps:
    - shell: sh
      run: |
        mkdir -p "$HOME/.appstoreconnect/private_keys"
        echo "${{ inputs.appstore_key_content }}" > "$HOME/.appstoreconnect/private_keys/AuthKey_${{ inputs.appstore_key_id }}.p8"
      
        xcrun altool --upload-app --file "${{ inputs.ipa_path }}" --apiKey "${{ inputs.appstore_key_id }}" --apiIssuer "${{ inputs.appstore_issuer }}"
        
